[control_plane]
k8s-test-control-01 ansible_host=192.168.0.234 k8s_private_ip=10.0.0.134 k8s_api_endpoint=10.0.0.134

[workers]
k8s-test-worker-01 ansible_host=192.168.0.241

[kubernetes:children]
control_plane
workers

[kubernetes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/gitlab-runner/.ssh/openstack_default_key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'