---
- name: Prepare Kubernetes nodes
  hosts: kubernetes
  become: true
  roles:
    - common

- name: Bootstrap Kubernetes control plane
  hosts: control_plane
  become: true
  roles:
    - control_plane

- name: Join Kubernetes workers
  hosts: workers
  become: true
  roles:
    - worker